'use strict';

// file automatically generated by angular-template-cache

import angular from 'angular';

const templatesModule = angular
	.module('widgetProject.template', [])
	.run(['$templateCache', function($templateCache) {
		$templateCache.put('home/home.ctrl.html', '<p>Welcome</p>');

		$templateCache.put('template/footer.html', '<h1>Footer</h1>');

		$templateCache.put('template/header.html', '<h1>Header</h1>');

		$templateCache.put('template/template.html', '<header ui-view="header" class="header"></header>\n' +
			'<div ui-view="content"></div>\n' +
			'<footer ui-view="footer" class="footer"></footer>');
	}
]);

export default templatesModule;
